# Generated by Django 2.2.1 on 2019-06-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_profile_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verify_email_slug',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
