# Generated by Django 2.2.1 on 2019-06-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_profile_verify_email_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
