# Generated by Django 2.2.1 on 2019-06-23 06:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0006_auto_20190615_1205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PayTM',
            new_name='Upi',
        ),
    ]
